# permissions for end users to view userprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userprofile-viewer-role
rules:
- apiGroups:
  - user.testapi.ashon.dev
  resources:
  - userprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.testapi.ashon.dev
  resources:
  - userprofiles/status
  verbs:
  - get
